import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Header from '@/components/Header';
import Faq from '@/components/seo/Faq';
import { guides } from '@/app/guides-data';

const content: Record<string,{intro:string; sections:Array<[string,string]>; faq:Array<{question:string;answer:string}>}> = {
 'what-are-ai-tokens': { intro:'AI tokens are pieces of text that a language model processes. They are not identical to words: punctuation, spaces, common word fragments and characters can be represented differently depending on the tokenizer.', sections:[['Tokens are not words','A sentence with ten words can contain more or fewer than ten tokens. Tokenizers split text according to the model family, vocabulary and encoding rules.'],['Why token counts matter','Many AI APIs price usage by tokens. Token counts also affect context-window capacity, so long prompts, retrieved documents and chat history can consume substantial capacity before a response is generated.'],['How to estimate tokens','A generic character-based ratio can be useful as a rough estimate, but it should not be presented as an exact provider count. A model-specific tokenizer or provider counting endpoint is preferable when available.']], faq:[{question:'Can I convert words directly into tokens?',answer:'Only approximately. The relationship varies with language, punctuation, code and tokenizer.'},{question:'Are tokens the same across AI models?',answer:'No. Different model families can use different tokenization methods.'}]},
 'how-ai-token-pricing-works': { intro:'AI APIs commonly separate input and output usage, and some pricing systems distinguish cached input from uncached input. A useful calculator should expose these variables instead of hiding them behind one number.', sections:[['Input tokens','Input tokens represent the material sent to the model, such as instructions, user text, conversation history and retrieved context.'],['Output tokens','Output tokens represent generated content. If output is priced differently from input, a longer answer can materially change the request cost.'],['Caching and other billing rules','Provider pricing can include cached-input discounts, batch pricing, regional rules, tools or other features. A calculator is therefore a planning tool, not a substitute for the provider billing dashboard.']], faq:[{question:'Why does my calculator differ from my provider bill?',answer:'The provider may count message envelopes, tools, cached tokens, rounding or other billable components that a plain-text calculator does not reproduce.'},{question:'Should I use the latest pricing?',answer:'Yes. Pricing changes over time, so verify current official provider pricing before making budget decisions.'}]},
 'context-windows-explained': { intro:'A context window is the amount of model input and output context that can be considered within a request. Large context limits are useful, but they do not make every long prompt free or automatically better.', sections:[['What consumes context','System instructions, user prompts, previous conversation turns, retrieved documents and expected/generated output can all affect context usage depending on the API and model.'],['Why remaining capacity matters','If a request is close to its context limit, there may be less room for the model to generate a response or for additional retrieved material.'],['Planning long-context workflows','Measure representative prompts, keep retrieval targeted, and monitor actual usage instead of assuming the maximum context window is always available for your desired output.']], faq:[{question:'Does context window equal maximum output?',answer:'Not necessarily. The available context is shared with the request and response according to the model and API behavior.'},{question:'Can a large context window reduce cost?',answer:'No. Context capacity and token pricing are separate concepts.'}]},
 'input-vs-output-tokens': { intro:'Input and output tokens describe two sides of an AI request. Many providers price them separately, which makes it useful to estimate both rather than looking only at prompt length.', sections:[['Input tokens','These are the tokens sent to the model. Long system prompts, chat history and retrieved context can increase input usage.'],['Output tokens','These are the tokens generated by the model. A request with a small prompt can still consume significant output tokens if the response is long.'],['Use both for budgeting','For realistic planning, estimate both sides and multiply by expected request frequency. Then compare the result with actual usage after launch.']], faq:[{question:'Which is usually more expensive?',answer:'It depends on the provider and model. Some pricing structures charge output tokens at a higher rate than input tokens.'},{question:'Can I reduce output tokens?',answer:'Yes. Clear output limits, concise formats and structured response requirements can reduce unnecessary generation.'}]},
 'how-to-reduce-ai-api-cost': { intro:'Reducing AI cost is usually about removing unnecessary token work rather than making every prompt as short as possible. Preserve the information the model needs and eliminate repetition that adds little value.', sections:[['Reduce repeated context','Avoid sending large instructions or conversation history when the API design lets you reuse or cache them appropriately.'],['Control output length','Ask for the required format and level of detail. Unbounded generation can become a significant part of usage.'],['Measure before optimizing','Use representative prompts and compare token volume, quality and latency. The cheapest request is not useful if it produces unusable output and has to be repeated.']], faq:[{question:'Should I always choose the cheapest model?',answer:'No. Compare cost with capability, reliability, latency and the quality needed for your task.'},{question:'Is shorter always better?',answer:'No. Removing essential context can reduce quality and create retries, which may increase total cost.'}]}
};

export function generateStaticParams() {
  return guides.map((g) => ({ slug: g.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const g = guides.find((x) => x.slug === slug);
  return g
    ? {
        title: g.title,
        description: g.description,
        alternates: { canonical: `/guides/${slug}` },
      }
    : {};
}

export default async function GuidePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const g = guides.find((x) => x.slug === slug);
  const c = content[slug];

  if (!g || !c) notFound();

  return (
    <>
      <Header />
      <main className="container section">
        <nav className="breadcrumbs" aria-label="Breadcrumb">
          <a href="/">Home</a>
          <span className="crumb-sep">/</span>
          <a href="/guides">Guides</a>
          <span className="crumb-sep">/</span>
          <span>{g.title}</span>
        </nav>
        <div className="eyebrow">Guide</div>
        <h1 style={{ fontSize: 'clamp(42px,6vw,64px)' }}>{g.title}</h1>
        <p className="section-intro">{c.intro}</p>
        <article className="article">
          <p>{c.intro}</p>
          {c.sections.map(([h, p]) => (
            <section key={h}>
              <h2>{h}</h2>
              <p>{p}</p>
            </section>
          ))}
          <div className="card related">
            <h3>Use TokenOrbit while you read</h3>
            <p>
              Try the{' '}
              <a className="text-link" href="/tools/ai-token-counter">
                AI token counter
              </a>
              , <a className="text-link" href="/tools/ai-cost-calculator">
                AI cost calculator
              </a>{' '}
              or{' '}
              <a className="text-link" href="/tools/context-window-calculator">
                context window calculator
              </a>{' '}
              with your own representative text.
            </p>
          </div>
        </article>
        <Faq items={c.faq} />
      </main>
    </>
  );
}
